import React, { ReactNode } from 'react'
import Head from 'next/head'

// component
import Header from './components/Header'
import Sidenav from './components/Sidenav'



const DashboardLayout = ({ children }: { children: ReactNode}) => {
	return (
		<div className="bg-[#F9F9F9] min-h-screen relative">
			<Head>
				<title>HB TASK - DASHBOARD</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			{/* Header */}
			<Header />
			
			<main className="min-h-screen max-w-full flex">
				{/* sidebar */}
				<Sidenav />

				<section className="main-content flex-grow max-w-full bg-white rounded-tl-lg ml-20">
					{ children }
				</section>
			</main>
			
		</div>
	)
}
export default DashboardLayout