import type { NextPage } from 'next'
import Head from 'next/head'
import SignUp from '../components/Auth/SignUp'

const Home: NextPage = () => {
  return (
    <div className="">
		<Head>
			<title>HB TASK</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>

		{/* Sign up screen */}
		<SignUp />
    </div>
  )
}

export default Home
